-- union of dashbd-indoorenv-sched-testweathercombine and
-- view_weather
-- [used by dashbd_indoorenv_weatherstation_hrly] 
CREATE VIEW dashbd_indoorenv_weatherstation AS 

 SELECT "dashbd-indoorenv-sched-testweathercombine".datetime,
    "dashbd-indoorenv-sched-testweathercombine".building,
    "dashbd-indoorenv-sched-testweathercombine"."Temperature_F",
    "dashbd-indoorenv-sched-testweathercombine"."Temperature_C",
    "dashbd-indoorenv-sched-testweathercombine"."Humidity_%",
    "dashbd-indoorenv-sched-testweathercombine"."Light (lux)",
    "dashbd-indoorenv-sched-testweathercombine"."CO2 (ppm)",
    "dashbd-indoorenv-sched-testweathercombine"."Power Avg (kW)",
    "dashbd-indoorenv-sched-testweathercombine"."Window",
    "dashbd-indoorenv-sched-testweathercombine"."Solar_radiation_w/m2",
    "dashbd-indoorenv-sched-testweathercombine"."Wind_speed_m/s",
    "dashbd-indoorenv-sched-testweathercombine"."Wind_direction_deg",
    "dashbd-indoorenv-sched-testweathercombine"."Barometric_pressure_hPa",
    "dashbd-indoorenv-sched-testweathercombine"."Dewpoint_C",
    "dashbd-indoorenv-sched-testweathercombine"."Dewpoint_F",
    "dashbd-indoorenv-sched-testweathercombine".instructor,
    "dashbd-indoorenv-sched-testweathercombine".teacher,
    "dashbd-indoorenv-sched-testweathercombine".class,
    "dashbd-indoorenv-sched-testweathercombine".dow,
    "dashbd-indoorenv-sched-testweathercombine".schoolday,
    "dashbd-indoorenv-sched-testweathercombine".session,
    "dashbd-indoorenv-sched-testweathercombine".type,
    "dashbd-indoorenv-sched-testweathercombine".appliance,
    "dashbd-indoorenv-sched-testweathercombine".room,
    "dashbd-indoorenv-sched-testweathercombine".surface,
    "dashbd-indoorenv-sched-testweathercombine".occ_sample,
    "dashbd-indoorenv-sched-testweathercombine".effective_occupancy,
    "dashbd-indoorenv-sched-testweathercombine"."time",
    "dashbd-indoorenv-sched-testweathercombine".date
   FROM "dashbd-indoorenv-sched-testweathercombine"
UNION ALL
 SELECT view_weather.datetime,
    view_weather.building,
    view_weather."Temperature_F",
    view_weather."Temperature_C",
    view_weather."Humidity_%",
    view_weather."Light (lux)",
    view_weather."CO2 (ppm)",
    view_weather."Power Avg (kW)",
    view_weather."Window",
    view_weather."Solar_radiation_w/m2",
    view_weather."Wind_speed_m/s",
    view_weather."Wind_direction_deg",
    view_weather."Barometric_pressure_hPa",
    view_weather."Dewpoint_C",
    view_weather."Dewpoint_F",
    view_weather.instructor,
    view_weather.teacher,
    view_weather.class,
    view_weather.dow,
    view_weather.schoolday,
    view_weather.session,
    view_weather.type,
    view_weather.appliance,
    view_weather.room,
    view_weather.surface,
    view_weather.occ_sample,
    view_weather.effective_occupancy,
    view_weather."time",
    view_weather.date
   FROM view_weather
  ORDER BY 1;
